<a href="https://colab.research.google.com/github/hamza1474/PracticeML/blob/master/IrisDataLogisticRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn as sk
from sklearn.datasets import load_iris
iris_dataset = load_iris()

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
iris_dataset['data'], iris_dataset['target'], random_state=0)

In [0]:
def Sigmoid(x):
  return 1/(1+np.exp(-x)) 

In [0]:
y_train.reshape(len(y_train),1)
y_test.reshape(len(y_test),1)
theta = np.zeros(5).reshape(5,1)
m = len(X_train)
z = np.ones((m,1))
X = np.append(z,X_train,axis=1)
all_theta = np.zeros(15).reshape(3,5)
alpha = 0.8

In [0]:
def CostFunction(X, y, theta):
  
  hofx = Sigmoid(X@theta)
  logExp = np.sum((np.transpose(np.log(hofx)) @ (-y_train.reshape(len(y_train),1))) - ((np.transpose(np.log(1-hofx)) @ (1-y_train.reshape(len(y_train),1)))))
  error = hofx - y.reshape(112,1)
  grad = ( np.transpose(X)@ error.reshape(len(error), 1) )/m
  return grad

In [0]:

def OneVsAll(X, y_train, alpha):
  for i in [0 ,1, 2]:
    theta = np.zeros(5).reshape(5,1)
    tempy = y_train == i
    y = tempy.astype(np.int)
    for j in range(1,30000):
      grad = CostFunction(X, y, theta)
      theta = theta - (alpha/m)*grad
    all_theta[i] = np.transpose(theta)
  return all_theta  
    

In [107]:
OneVsAll(X, y_train, alpha)

array([[ 0.40208403,  0.64273854,  2.09047147, -3.34638045, -1.52726104],
       [ 1.73731359,  0.5789863 , -2.06917854,  0.7085316 , -2.10369185],
       [-1.80117413, -3.01028323, -2.26861874,  4.31177618,  3.79373964]])

In [0]:
ones = np.ones((len(X_test),1))
X2 = np.append(ones,X_test,axis=1)
Prediction = []

In [109]:
r = X2 @ np.transpose(all_theta);
result = Sigmoid(r);
for i in range(len(result)):
    Prediction.append(np.where(result[i] == np.amax(result[i])))

result


array([[2.14732928e-05, 1.05872290e-01, 9.95856591e-01],
       [2.34007302e-03, 8.00508122e-01, 2.16049654e-02],
       [9.99559316e-01, 3.92559223e-02, 6.92511695e-10],
       [3.12890581e-06, 6.54843776e-01, 9.74361451e-01],
       [9.95496366e-01, 1.46677293e-01, 2.94821218e-08],
       [3.55716678e-06, 7.93360890e-02, 9.99177719e-01],
       [9.97815004e-01, 8.94885114e-02, 1.44969881e-08],
       [1.07970637e-03, 3.49015175e-01, 4.53544288e-02],
       [5.12977537e-04, 5.83340959e-01, 6.81493231e-02],
       [5.51445955e-03, 3.95262855e-01, 1.29060630e-02],
       [1.48146227e-05, 7.13383525e-01, 9.67543875e-01],
       [2.14068978e-03, 2.41277021e-01, 3.79438839e-02],
       [6.20358718e-04, 5.69815493e-01, 1.54700679e-01],
       [7.08935396e-04, 4.52823799e-01, 1.00167246e-01],
       [5.63377456e-04, 4.14217390e-01, 2.37522147e-01],
       [9.98053048e-01, 1.09767202e-01, 1.12519005e-08],
       [8.85279874e-04, 3.19399690e-01, 2.06154079e-01],
       [7.57737583e-04, 5.33694

In [110]:
sum = 0
for x in (y_test - np.transpose(Prediction)).reshape(38,1):
  if x == 0:
    sum+=1
acc = (sum/38)*100    
print("The accuracy is ", acc)

The accuracy is  92.10526315789474


In [99]:
y_test

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 1])